[[constraint]]
  name = "github.com/DataDog/dd-trace-go"
  version = "0.6.1"

[[constraint]]
  branch = "master"
  name = "github.com/afex/hystrix-go"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.1"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
